name: Weixin_time_push_for_lty
on:
  workflow_dispatch:
  schedule: 
    # 代表UTC 11h28m，Toronto Time and NYC time -4, which is 7h28m AM
    - cron: '28 11 * * *'
jobs:
#将工作流程中运行的所有作业组合在一起
  build:
  #定义名为 build 的作业。 子键将定义作业的属性 
    runs-on: ubuntu-latest 
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
    
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Weixin_time_push_for_lty
        run: |
          python3 main.py
